# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7738593d17f7c8b5184e3e15b1a773062b9caeee206336c3a1d2a84fd9a540c925d64c848dab959075c93808c138f6d4a8627aeb0becda7d7dec025e90b72c01

test:
  secret_key_base: 2ba30887e9df17a32573be845edc91b6c6804f49b6c148f23d04832340a21d67ae3b150c4d04f963ee6d89d4e3de9605956c92d3b5209b1a5acfd0bff7f7f6ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
